{{- if and .Values.proxy.https.enabled (eq .Values.proxy.https.type "manual") .Values.proxy.https.manual.cert .Values.proxy.https.manual.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loomai.proxy.fullname" . }}-manual-tls
  labels:
    {{- include "loomai.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.proxy.https.manual.cert | b64enc }}
  tls.key: {{ .Values.proxy.https.manual.key | b64enc }}
{{- end }}
