apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "loomai.hub.fullname" . }}-db
  labels:
    {{- include "loomai.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.hub.db.pvc.storageClass }}
  storageClassName: {{ .Values.hub.db.pvc.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.hub.db.pvc.capacity }}
