apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loomai.hub.fullname" . }}-secret
  labels:
    {{- include "loomai.labels" . | nindent 4 }}
    app.kubernetes.io/component: hub
type: Opaque
stringData:
  CILOGON_CLIENT_ID: {{ .Values.auth.cilogon.clientId | quote }}
  CILOGON_CLIENT_SECRET: {{ .Values.auth.cilogon.clientSecret | quote }}
  COOKIE_SECRET: {{ include "loomai.cookieSecret" . | quote }}
  PROXY_AUTH_TOKEN: {{ include "loomai.proxyToken" . | quote }}
  FABRIC_CORE_API_BEARER_TOKEN: {{ .Values.auth.fabricCoreAPI.bearerToken | quote }}
