{{- if .Values.scheduling.userScheduler.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "loomai.fullname" . }}-user-scheduler
  labels:
    {{- include "loomai.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-scheduler
{{- end }}
